src/MatchesSnapshots.php
- Changed updating of snapshots to use `-d --update` when running `phpunit`.
- Fixed usage of non-existant `$snapshot->update()` method
---
We  had our [own package](https://github.com/madewithlove/phpunit-snapshots) for this, but yours is more feature complete. This PR fixes the updating of snapshots and adds a better API to update
=> Easier to use update API

src/Filesystem.php
In larger projects, i split up my snapshots in subdirectories by overriding the `getSnapshotDirectory` and `getFileSnapshotDirectory` methods. 
I ran into the problem today that i tried creating a snapshot in a subdirectory, but the `__snapshots__` directory didn't exist yet, which caused `mkdir()` to fail.
=> Allow recursive mkdir

src/Snapshot.php, tests/Unit/SnapshotTest.php
If The test uses Data Providers with titles. 
Then the Filename includes invalid Characters:
filename: ``ClassTest__testOne with data set "Empty"__1.php``
With this fix the file name will be sanitized and look like this:
``ClassTest__testOne with data set Empty__1.php``
Minimum reproducible TestClass:
````php
<?php
class ClassTest extends \PHPUnit\Framework\TestCase
{
use \Spatie\Snapshots\MatchesSnapshots;
/**
* @dataProvider dataProvider
* @param string $first
*/
public function testOne(string $first)
{
$this->assertMatchesSnapshot(print_r($first, true));
}
public function dataProvider()
{
return [
'Empty' => [''],
];
}
}
````
=> [BUGFIX] sanitize filename

src/MatchesSnapshots.php
https://github.com/spatie/phpunit-snapshot-assertions/pull/43 changed the way updating snapshots is handled. Now, if you update a failed file-snapshot, the test will fail. This happens because the old code threw an exception, but the new code doesn't. Adding a `return` fixes this.
Edit: added another `return` statement when a new file-snapshot is created
=> Fix updating failed file-snapshots

tests/Unit/Drivers/VarDriverTest.php
Update using version compare for greater than 7.3.0
=> Update VarDriverTest for PHP 7.3

composer.json, tests/Integration/AssertionTest.php, tests/Integration/MatchesSnapshotTest.php, tests/Unit/SnapshotTest.php
The proposal is the support of PhpUnit 8 and php 7.2 _(or newer)_ requirement. [Active support for PHP 7.1 ended on December 1, 2018](https://secure.php.net/supported-versions.php)
=> Upgrade PHPUnit from 7 to 8 (php 7.2 required)

src/Drivers/JsonDriver.php, tests/Integration/AssertionTest.php
The recent update to allow arrays to be asserted against is using an undefined variable.
I have added a test to check that an array can be matched against and updated the variable.
=> Added test to check the JSON driver can take an array.

src/Drivers/JsonDriver.php, tests/Integration/AssertionTest.php
Cherry picks https://github.com/spatie/phpunit-snapshot-assertions/commit/9e77852202fc057bcd5b61d91ca897ac4301206b into v1 to fix the JsonDriver when taking an array $actual param.
=> Fix JsonDriver for v1

composer.json, phpunit.xml.dist
As PHPUnit 9 has been released, I was wondering if `phpunit-snapshot-assertions` would be easily portable and as it turns out, it is ;-)
Only point was: `tap` is not a supported log type anymore and PHPUnit will therefore not create that `build/report.tap` file anymore. I removed this from the `phpunit.xml.dist` file and hope this is ok.
=> Add support for PHPUnit 9

README.md, composer.json, src/MatchesSnapshots.php, tests/Integration/MatchesSnapshotTest.php
by passing `--no-create-snapshots`
Fix #93
I took advantage of this to fix some syntax issue, deprecation, and improve tests.
=> Add the ability to disable snapshots creation.

.gitattributes, .github/workflows/run-tests.yml, composer.json, src/Drivers/JsonDriver.php, tests/Unit/Drivers/HtmlDriverTest.php, tests/Unit/Drivers/JsonDriverTest.php, tests/Unit/Drivers/ObjectDriverTest.php, tests/Unit/Drivers/XmlDriverTest.php, tests/Unit/Drivers/YamlDriverTest.php
The core of this PR is 66584f9 commit, everything else is to make tests run on Windows.
It fixes inconsistent EOLs in JSON snapshots on Windows by replacing OS-dependent `PHP_EOL` with `\n`.
`json_encode` with `JSON_PRETTY_PRINT` flag always use `\n` regardless of OS, but `PHP_EOL` yields `\r\n` on Windows causing inconsistent line ends and unnecessary diff for git, if files are regenerated.
All other commits are about making tests consistent between Linux and Windows by always using LF line ending. 
---
As a side note, it also revealed inconsistent behaviour between drivers. On Windows, most of the integration tests for JSON were passing regardless of line ending while other drivers failed, which is given by using `Assert::assertEquals` vs `Assert::assertJsonStringEqualsJsonString` in …
=> Fix inconsistent line endings in JSON snapshots

src/Concerns/SnapshotDirectoryAware.php, src/Concerns/SnapshotIdAware.php, src/MatchesSnapshots.php
While developing [pest-plugin-snapshots](https://github.com/spatie/pest-plugin-snapshots) I need to override both `getSnapshotDirectory` and `getSnapshotId` without actually using inheritance.
This pull request moves both methods to specific traits, allowing pest-plugin-snapshots to override those two methods using composer autoload: https://github.com/spatie/pest-plugin-snapshots/pull/2.
Let me know if something is not clear.
Once you merge this pull request, please release a new **v4.2.2** version. As this can be consider as a small refactor.
=> Moves default implementation of snapshot directory/id to concerns directory

.github/workflows/run-tests.yml, composer.json, phpunit.xml.dist
Hey guys,
as you might know, the php 8 release is around the corner. As this package is designated to testing I thought it's a good idea to already adjust the composer php version constraint to allow php 8, as many maintainers which are using this very package surely want to start preparing for php 8 soon. All dependencies already support it and the builds for both php 7.4 and 8.0 dev are all green.
=> Allow php 8

src/Drivers/HtmlDriver.php
Discovered an error similar to the one reported here: https://github.com/spatie/phpunit-snapshot-assertions/pull/97
Just seems to be failing tests due to Windows line endings being used.
Example failing tests result: https://github.com/mallardduck/blade-boxicons/runs/5114345425?check_suite_focus=true
=> Normalize windows line endings on HTML tests

src/Drivers/JsonDriver.php
I'm using Intellij Idea when using the assertEquals and providing two arrays it does automatically do a diff and we can get a diff view, I'm sure other ides do too, but for strings comparison diff view is not either shown or is really messy and useless for big json objects, so this fixes all that.
Also fixes one of the issues of the other PR : https://github.com/spatie/phpunit-snapshot-assertions/pull/135#issuecomment-1071372599 and is backward compatible too. (no breaking changes, can work on all encode options.)
Before : 
After :
=> revert match process in JsonDriver

src/Drivers/HtmlDriver.php, tests/Unit/Drivers/HtmlDriverTest.php
=> Use `LIBXML_HTML_NODEFDTD` to maintain output consistency

composer.json, tests/Unit/Drivers/HtmlDriverTest.php
This PR should help prevent any future regression and adds a test to cover previously untested behavior. This is a follow up to unexpected breaks in #141 that affects certain input. Additionally this adds the XML extension as an explicit requirement as it's now being used after 141 as well.
=> Add test to cover HTML without doctype

src/Drivers/JsonDriver.php, tests/Unit/Drivers/JsonDriverTest.php
At the moment there is no type-safe check in the JsonDriver. If the data type of a field that can be converted internally by PHP (e.g. numeric strings), the test does not fail as expected.
=> Add type safe json matching

src/Drivers/TextDriver.php, tests/Unit/Drivers/TextDriverTest.php
~Initially this PR will just be adding tests - in theory these tests will add a failing condition to windows runs only. This gives us a TDD based target to verify the patch I have in mind.~
This PR applies a fix similar to #136, however it applies to the Text driver. This PR will fix bugs encountered in CI environments like this: https://github.com/KickflipCli/kickflip-src/runs/7523509151?check_suite_focus=true#step:10:22
=> Add tests for Text Driver and Windows EOL fixes

src/Filename.php, tests/Unit/FilenameTest.php
If PCRE_UTF8 is not used in the filename cleaning process, unexpected characters may be erased.
I found this when using Japanese in the data set.
=> Apply PCRE_UTF8 for cleaning filename

src/Concerns/SnapshotIdAware.php
Add the data set name to the snapshot file names to generate separate snapshot files when dataProviders are used. 
This should fix #162 and probably #161
=> Generate snapshot file names with dataset

README.md
Previously suggested `.gitattributes` value would remove all `0D` byte sequences (same as linefeed) from binary files (e.g. PDF) on Windows.
=> Update windows users info in readme.md

src/MatchesSnapshots.php
The former will not work with 10.1 anymore, according to phpunit this was an unintended side effect, see https://github.com/sebastianbergmann/phpunit/issues/5337#issuecomment-1513000069
Fixes https://github.com/spatie/phpunit-snapshot-assertions/issues/167
The test suite in this framework does not cover the presence of this phpdoc (when I removed it, all tests were still green).
Upfront I tested this in a local installation of phpunit-snapshot-assertions (though it was an older version, still using PHP 7.4 there), but I could already confirm even for that version and PHPUnit <10 in that case, it worked.
=> Change `@after` to `@postCondition`

composer.json, src/MatchesSnapshots.php
- Expand version constraint to allow phpunit 11, [just released](https://phpunit.de/announcements/phpunit-11.html)
- Check the action with "prefer-stable" and we see it picks phpunit 11
E.g. https://github.com/spatie/phpunit-snapshot-assertions/actions/runs/7761804048/job/21170990782?pr=185#step:6:22
> `- Locking phpunit/phpunit (11.0.1)`
"prefer-lowest" OTOH still picks phpunit 10
- The change in `MatchesSnapshots.php` is done by the bot, not by me
=> Allow phpunit 11

src/Drivers/JsonDriver.php, tests/Unit/Drivers/JsonDriverTest.php
We have lot of snapshots containing links. I am sure it will be much easier to read them if they are unescaped. Most languages do not do these escapings by default, PHP does it because of some security-wise XSS edge cases that are not relevant here.
=> Improve readability of generated JSON snapshots

src/Drivers/ObjectDriver.php, tests/Unit/Drivers/ObjectDriverTest.php
=> Allow setting yamlInline for ObjectDriver

src/MatchesSnapshots.php
This PR removes the strict type annotation from the `$actual` parameter in `assertMatchesJsonSnapshot()` to allow any JSON-serializable value, including `JsonSerializable` objects.
The underlying `JsonDriver` already accepts mixed input, so this change relaxes the input constraint to better reflect its capabilities. It also improves consistency with other `assertMatches*Snapshot` methods, which do not restrict input types.
=> Allow `assertMatchesJsonSnapshot` to accept any JSON-serializable value
